spring:
  rabbitmq:
    addresses: 8.136.110.11:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://8.136.110.11:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.110.11:8848
  redis:
    host: 8.136.110.11
    port: 6380
    password: 123456
mybatis:
  mapper-locations: classpath:com.springcloud.ufire.core.mapper/*.xml
