server:
  port: 9876
spring:
  application:
    name: ufire-websocket-ui
  cloud:
    nacos:
      discovery:
        server-addr: 172.66.0.66:8848
#prd
app:
  wssUrl: ws://websocket.ufiredong.cn/ufire-websocket/socket/
  messageUrl: http://websocket.ufiredong.cn/ufire-websocket/websocket/to/